### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [natasha-shurlina/Java#1]
1. Настроек локальной среды разработки (`.idea`, `*.iml`) в репозитории быть не должно.
2. А что за пустой файлик `text3.txt` в корне репозитория?
3. У вас по проекту много где раскиданы файлики `*.txt`. Если это данные для тестов, то лучше завести какую-то директорию в корне проекта вида `testData`, и всё это переложить туда.
4. В java принято назвать переменные с помощью `camelCase`. [link](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/main/java/Main.java#L7)
5. А зачем одно и то же два раза? [link](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/main/java/Main.java#L14)
6. Отладочные принты лучше убрать. [link](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/main/java/Main.java#L27)
7. По заданию, нужно находить все файлы с таким именем, а не только первый. 
8. Лучше сделать это всё не статическим. [link](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/main/java/Main.java#L40)
9. Чтобы в [подобных](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/main/java/Main.java#L46) случаях не росла вложенность обычно делают вот так: 
```java
if (!dir.exists()) {
    System.out.println("Указанная дирректория не существует");
    return null;
}
```
10. Абсолютные пути лучше ни где не задавать. Они делают код не переносимым.  Например, если я попробую запустить ваши тесты на своём компьютере, то всё упадёт, потому что у меня нет такого абсолютного пути. [link](https://github.com/natasha-shurlina/Java/blob/89eb9c3d06df90dad29087a8d5945c07c76320d0/src/test/java/SearcherTest.java#L11)

**Comment by Saloed** [comment]
1. Может [здесь](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L46) тоже применить такой же подход, как в пункте 9 предыдущего списка?
2. Вот [этот](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L52) и [этот](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L69) куски кода очень похожи. Может как-то реорганизовать код, чтобы их не дублировать?
3. А зачем возвращать строку? [link](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L81)
4. А зачем, приведение к типу `String` вот [здесь](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L54)?
5. Кажется, здесь может вылетать `IndexOutOfBounds`. [link](https://github.com/natasha-shurlina/Java/blob/90dac2fea190428e17b0469369882b8b827f7ec4/src/main/java/Main.java#L18)

**Comment by Saloed** [comment]
Замечание 2 из прошлого списка не исправлено

**Comment by natasha-shurlina** [comment]
Исправила
